### ISSUE TITLE
Дубликат доклада?

### ISSUE THREAD

**Issue by ilabutin** [DotNetRu/Audit#226]
Вижу два доклада Ромы Неволина, похоже на дубликат:
https://github.com/DotNetRu/Audit/blob/master/db/talks/Why-your-architecture-is-functional.xml
https://github.com/DotNetRu/Audit/blob/master/db/talks/Why-is-Your-Architecture-Functional.xml

Первый правильный (на него есть ссылка из митапа)

**Comment by kulakovt** [comment]
Первый доклад читался на `MskDotNet-38`, второй на `NnvDotNet-1`.

Фактически это разные версии одного и того же доклада. К сожалению у нас нет формальных признаков для классификации подобных докладов. А очень бы хотелось, ибо ситуация не редкая. Если есть идеи, предлагайте.

**Comment by kulakovt** [comment]
@ilabutin , закрываем?

**Comment by ilabutin** [comment]
Да, согласен.
