### ISSUE TITLE
Radiodotnet: съезжает md разметка

### ISSUE THREAD

**Issue by MaxShoshin** [DotNetRu/Audit#249]
Сейчас выглядит так:

Number: 32 Title: Исцеление памяти, обсуждение сетей, странный GraphQL PublishDate: 2021-07-14T21:26:20Z Authors:

- Анатолий Кулаков

- Игорь Лабутин Mastering: Максим Шошин Music: Максим Аршинов «Pensive yeti.0.1»: https://hightech.group/ru/about Patrons:

- Александр

- Сергей

А наверное хочется чтобы выглядело так:

Number: 32 
Title: Исцеление памяти, обсуждение сетей, странный GraphQL 
PublishDate: 2021-07-14T21:26:20Z 
Authors:
- Анатолий Кулаков
- Игорь Лабутин 
 
Mastering: Максим Шошин 
Music: Максим Аршинов «Pensive yeti.0.1»: https://hightech.group/ru/about 

Patrons:
- Александр
- Сергей

**Comment by kulakovt** [comment]
@MaxShoshin , кнопочку Raw нажми
![image](https://user-images.githubusercontent.com/11032050/127669750-572039fd-3f75-47e9-b3ae-a4d8e346a877.png)

Это про GitHub плохо рендерит YAML front matter.

**Comment by kulakovt** [comment]
@MaxShoshin , закрываем?

**Comment by MaxShoshin** [comment]
Не.... Нужна ссылка issue заведенное на гитхаб.
Или поправить чтобы правильно отображалось

**Comment by kulakovt** [comment]
@MaxShoshin Ну заведи.

Какое отношение это имеет к данному репозиторию? Эти файлы не для отображения в браузере. Аудит — для роботов весь, без исключения. Нет задачи красиво читать людьми, иначе их бы не в YAML'е писали и не в XML'е.

**Comment by kulakovt** [comment]
Цели отображать служебные файлы красиво в интерфейсе GitHub не ставилось.
