### ISSUE TITLE
Удалить Obsolete код, после полного перехода на Сессии

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/Audit#34]
После того как App перейдёт на Сессии (DotNetRu/App#81) необходимо удалить устаревший код модели:

- [Дата Встречи](https://github.com/AnatolyKulakov/Boombr/blob/master/src/Model.ps1#L58)
- [Cписок Докладов на Встречи](https://github.com/AnatolyKulakov/Boombr/blob/master/src/Model.ps1#L65)

**Comment by pfedotovsky** [comment]
@AnatolyKulakov мобильное приложение перешло на сессии (develop бранч), после релиза в магазины можно будет почистить Audit
