### ISSUE TITLE
Расширить информацию о сообществах

### ISSUE THREAD

**Issue by pfedotovsky** [DotNetRu/Audit#42]
Сейчас в Audit нет хватает информации о сообществах, e.g. нет ссылок на VK группу, Twitter, Slack, Facebook и др.

Нужно собрать информацию у активистов сообществ и добавить ее в Audit.

**Comment by AnatolyKulakov** [comment]
Готово. Добавил возможность иметь:

- VkUrl
- TwitterUrl
- TelegramChannelUrl
- TelegramChatUrl
- MeetupComUrl
- TimePadUrl

Полный список смотри в [Community.xsd](https://github.com/DotNetRu/Audit/blob/master/schemas/Community.xsd#L13-L18).
