### ISSUE TITLE
Расширить митап ссылкой на страницу регистрации

### ISSUE THREAD

**Issue by pfedotovsky** [DotNetRu/Audit#56]
Сейчас используюя приложение DotNetRu можно оперативно узнать о новом митапе. Но к сожалению, зарегистрироваться на митап прямо через приложение нельзя, т.к. нет ссылки на регистрацию в митапе. Поэтому пользователю нужно искать ссылку в других местах, что не очень удобно.

Хочется получить ссылку на регистрацию из митапа, чтобы приложение могло ее отобразить. Таким образом, пользователь сможет оперативно зарегистрироваться на встречу.

**Comment by AnatolyKulakov** [comment]
Непосредственно в сам Audit ссылку на TimePad вставлять не хочется. Ибо анонс всех мероприятий должен в будущем генерироваться из Audit'а. Такое кольцо зависимостей ни к чего хорошему не приведёт.

Но проблема актуальная. Вижу два пути решения:

1. дождаться запуска [Server'а](https://github.com/DotNetRu/Server), у него должны быть эти знания и он может раздавать их через API;
1. воспользоваться TimePad API и сопоставить открытые анонсы по номеру митапа или дате.

**Comment by AnatolyKulakov** [comment]
Я добавил ссылку на домашнюю TimePad страничку в Сообщество. Так нет никаких конфликтов. Думаю, что с помощью AI и ML можно получить список предстоящих митапов и дополнительно отфильтровать их по номеру.
